rpdesign/appRP/urls.py
from django.urls import path
from . import views

app_name = 'appRP'

urlpatterns = [
    path('', views.index, name='inicio'),
    path('decoracion/', views.decoracion, name='decoracion'),
    path('<int:id>/<slug:slug>/', views.producto_detalle, name='producto_detalle'),
    path('contacto/', views.contacto, name='contacto'),

    path('login/', views.logueo, name='login'),
    path('logout/', views.deslogueo, name='logout'),

    path('alta_usuario/', views.alta_usuario, name='alta_usuario'),
    path('editar_usuario/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    
    path('alta_producto/', views.alta_producto, name='alta_producto'),
    path('edita_producto/<int:producto_id>/', views.edita_producto, name='edita_producto'),
    path('elimina_producto/<int:producto_id>', views.elimina_producto, name='elimina_producto'),
    path('productos/', views.productos, name='productos'),

    path('carrito/', views.carrito_detalle, name='carrito_detalle'),
    path('carrito/add/<int:producto_id>/', views.carrito_add, name='carrito_add'),
    path('carrito/remove/<int:producto_id>/', views.carrito_remove, name='carrito_remove'),

    path('crear/', views.crear_orden, name='crear_orden'),
    path('proceso_pago/', views.proceso_pago, name='proceso_pago'),
    path('orden_cancelada/<int:orden_id>', views.orden_cancelada, name='orden_cancelada'),
    path('completado/', views.pago_completado, name='completado'),
    path('cancelado/', views.pago_cancelado, name='cancelado'),

    path('error/', views.error, name='404'),
]

rpdesign/rpdesign/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('rpadmin/', admin.site.urls),
    path('', include('appRP.urls', namespace='appRP')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rpdesign/appRP/forms.py
from django import forms
from .models import Usuario, Producto, Orden

from django.contrib.auth.forms import UserCreationForm

FORMATOS = [(0, 'Seleccione un formato'),
            ('15 cm x 20 cm', '15 cm x 20 cm'),
            ('20 cm x 25 cm', '20 cm x 25 cm'),
            ('30 cm x 40 cm', '30 cm x 40 cm')]

class AltaProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = '__all__'
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':"form-control", 'id':"name", 'placeholder':"nombre", 'required':True}),
            'descripcion' : forms.TextInput(attrs={'class':"form-control", 'id':"description", 'placeholder':"descripción", 'required':True}),
            'formato' : forms.Select(attrs={'class':"form-select", 'id':"format"}, choices=FORMATOS),
            'precio' : forms.NumberInput(attrs={'class':"form-control", 'id':"price", 'placeholder':"100", 'required':True}),
            'imagen' : forms.FileInput(attrs={'class':"form-control", 'id':"linkPhoto",}),
                }


class AltaUsuario(UserCreationForm):

    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'email', 'dni', 'username', 'calle', 'altura', 'piso', 
            'depto', 'localidad', 'cod_postal', 'password1', 'password2']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            # Recorremos todos los campos del modelo para añadirle class="form-control
            self.fields[field].widget.attrs.update({'class': 'form-control'})

        # Añadir atributos personalizados a un campo.
        self.fields['first_name'].widget.attrs.update({'placeholder': 'nombre'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'apellido'})

    def clean_username(self):
        username = self.cleaned_data['username']
        username_taken = Usuario.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('El nombre de usuario ya esta en uso.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        email_taken = Usuario.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('El email ya esta en uso.')
        return email

    def clean_dni(self):
        dni = self.cleaned_data['dni']
        dni_taken = Usuario.objects.filter(dni=dni).exists()
        if dni_taken:
            raise forms.ValidationError('El dni ya esta en uso.')
        return dni


class ModificaUsuario(forms.ModelForm):
    
    class Meta:
        model = Usuario
        # Los campos a modificar, excepto "password".
        fields = ['first_name', 'last_name', 'email', 'dni', 'username', 
                'calle', 'altura', 'piso', 'depto', 'localidad', 'cod_postal']
        

# FORMULARIOS PARA EL CARRITO

CANTIDAD_PRODUCTO = [(i, str(i)) for i in range(1, 21)]

class CarritoAgregaProducto(forms.Form):
    cantidad = forms.TypedChoiceField(
                                choices=CANTIDAD_PRODUCTO,
                                coerce=int)
    anular = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)
    

# FORMULARIO PARA LAS ORDENES

class CrearOrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['first_name', 'last_name', 'email', 'calle', 'altura', 'piso',
                     'depto', 'localidad', 'cod_postal']
        labels = {'first_name': 'Nombre', 'last_name': 'Apellido', }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            # Recorremos todos los campos del modelo para añadirle class="form-control
            self.fields[field].widget.attrs.update({'class': 'form-control'})

rpdesign/appRP/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.core.mail import EmailMultiAlternatives

from appRP.models import Producto, Usuario, OrdenItem, Orden
from appRP.carrito import Carrito
from appRP.forms import AltaProducto, AltaUsuario, ModificaUsuario, CarritoAgregaProducto, CrearOrdenForm
from django.contrib import messages

from django.views.decorators.http import require_POST

from django.conf import settings

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
import mercadopago

# Create your views here.

def index(request):
    context = {'barra': 'nav'}
    return render(request,'appRP/publica/index.html', context)

def decoracion(request):
    # ordenados de manera descendente
    # productos = Producto.objects.all().order_by('-id')
    # ordenados de manera ascendente(por defecto) 
    # productos = Producto.objects.all().order_by('id')
    productos = Producto.objects.filter(disponible=True).order_by('id')
    context = {'barra': 'nav2', 'lalista': productos}
    return render(request, 'appRP/publica/decor.html', context,)

def producto_detalle(request, id, slug):
    producto = get_object_or_404(Producto, id=id, slug=slug, disponible=True)
    carrito_producto_form = CarritoAgregaProducto()
    context = {'barra': 'nav2', 'producto': producto, 'carrito_producto_form': carrito_producto_form}
    return render(request, 'appRP/publica/detalle.html', context)

def contacto(request):
    context = {'barra': 'nav2'}
    return render(request,'appRP/publica/contact.html', context)

def logueo(request):
    if request.user.is_authenticated:
        return redirect("/")
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
            # Password correcto, y usuario marcado como "active"
                request.user = user
                login(request, user)
            # Redirecciono a la galeria
                return redirect("/decoracion")
            else:
            # Muestro un mensaje de error
                form = AuthenticationForm()
                messages.error(request, 'Se ha producido un error al autenticarse, Nombre de usuario ó Contraseña incorrectos')          
                return redirect("/login")
        else:
            form = AuthenticationForm()
    return render(request,'appRP/publica/login.html', {'form': form})

def deslogueo(request):
  if request.user.is_authenticated:
    logout(request)
    messages.success(request,"Se ha deslogueado correctamente")
  return redirect("/login")

@require_POST
def carrito_add(request, producto_id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=producto_id)
    form = CarritoAgregaProducto(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        carrito.add(producto=producto,
                    cantidad=cd['cantidad'],
                    anular_cantidad=cd['anular'])
    return redirect('appRP:carrito_detalle')

@require_POST
def carrito_remove(request, producto_id):
    carrito = Carrito(request)
    producto = get_object_or_404(Producto, id=producto_id)
    carrito.remove(producto)
    return redirect('appRP:carrito_detalle')

@login_required(login_url=settings.LOGIN_URL)
def carrito_detalle(request):
    if request.user.is_authenticated:
        carrito = Carrito(request)
        for item in carrito:
            item['actualizar_cantidad_form'] = CarritoAgregaProducto(initial={
                                                                    'cantidad': item['cantidad'],
                                                                    'anular': True})
        return render(request, 'appRP/publica/carrito.html', {'carrito': carrito})
    else:
        return redirect('appRP:404')
    
@login_required(login_url=settings.LOGIN_URL)
def crear_orden(request):
    if request.user.is_authenticated:
        carrito = Carrito(request)
        if request.method == 'POST':
            form = CrearOrdenForm(request.POST)
            if form.is_valid():
                orden = form.save()
                for item in carrito:
                    OrdenItem.objects.create(orden=orden,
                                            producto=item['producto'],
                                            precio=item['precio'],
                                            cantidad=item['cantidad'])
                # Vacio el carrito
                carrito.clear()
                # almaceno la orden en la sesion
                request.session['orden_id'] = orden.id
            # redirecciono para pagar
            return redirect(reverse('appRP:proceso_pago'))
        else:
            envio = 1500.00
            usuario = Usuario.objects.get(id=request.user.id)
            form = CrearOrdenForm(instance=usuario)
        return render(request,'appRP/publica/crear.html', {'carrito': carrito, 'form': form , 'envio': envio})
    else:
        return redirect('appRP:404')

@login_required(login_url=settings.LOGIN_URL)
def proceso_pago(request):
    if request.user.is_authenticated:
        sdk = mercadopago.SDK(settings.ACCESS_TOKEN)
        orden_id = request.session.get('orden_id', None)
        orden = get_object_or_404(Orden, id=orden_id)
        exito_url = request.build_absolute_uri(reverse('appRP:completado'))
        fallo_url = request.build_absolute_uri(reverse('appRP:cancelado'))
        # Creo los datos de la preferencia
        preference_data = {
                    "back_urls": 
                        {
                    'failure': fallo_url, 
                    'pending': '', 
                    'success': exito_url,
                        },
                    'auto_return': 'approved',
                    'binary_mode': True,
                    'external_reference': orden.id,
                    'items': [{
                                'title': 'envio',
                                'quantity': 1,
                                'unit_price': float(1500.00),
                                'currency_id': 'ARS',
                                'description': 'Costo de envio',
                                        }],
                    "payment_methods": {
                            "excluded_payment_types": [
                                {
                                    "id": "ticket"
                                }
                            ],
                            "installments": 3
                        },
        }
        # agregar items de la orden
        for dato in orden.items.all():
            preference_data['items'].append({
                                    'title': dato.producto.nombre,
                                    'quantity': dato.cantidad,
                                    'unit_price': float(dato.precio),
                                    'currency_id': 'ARS',
                                    'description': dato.producto.nombre,
                                            })
        preference_response = sdk.preference().create(preference_data)
        preference = preference_response["response"]
        id = preference["id"]
        envio = 1500.00
        return render(request, 'appRP/publica/proceso_pago.html', locals())
    else:
        return redirect('appRP:404')

@login_required(login_url=settings.LOGIN_URL)
def pago_completado(request):
    collection_status = request.GET['collection_status']
    external_reference = request.GET['external_reference']
    envio = {'title': 'envio',
            'quantity': 1,
            'unit_price': float(1500.00),
            'currency_id': 'ARS',
            'description': 'Costo de envio',}
    if collection_status == 'approved':
        try:
            orden = Orden.objects.get(id=request.GET['external_reference'])
        except Orden.DoesNotExist:
            return redirect('appRP:404')
        # marco la orden como pagada
        orden.pagada = True
        orden.save() 
        # genero la info para el mail
        data = {
            'items':[],
            }
        for dato in orden.items.all():
            data['items'].append({
                                'title': dato.producto.nombre,
                                'quantity': dato.cantidad,
                                'unit_price': float(dato.precio),
                                'currency_id': 'ARS',
                                'description': dato.producto.nombre,
                                        })
        subject = f'Orden de compra Nro. {orden.pk}'
        template = loader.get_template('appRP/publica/correo.html')
        content = template.render({
            'orden':orden, 
            'envio':envio,
        })
        message = EmailMultiAlternatives(subject, #Titulo
                                        content,
                                        settings.EMAIL_HOST_USER, #Remitente
                                        [settings.RECIPIENT_ADDRESS, orden.email],#Destinatario
                                        )                                            
        message.attach_alternative(content, 'text/html')
        message.send() 
    return render(request, 'appRP/publica/completado.html', {'collection_status': collection_status,
                                                             'external_reference': external_reference, 
                                                             'orden':orden, 
                                                             'envio':envio })

@login_required(login_url=settings.LOGIN_URL)
def pago_cancelado(request):
    return render(request, 'appRP/publica/cancelado.html')

rpdesign/templates/appRP/publica/alta_producto.html
{% extends './base.html' %}

{% block titulo %} - Alta productos {% endblock titulo %}

{% block contenido %}

<main>
    <div class="container3">
        <div class="separador"></div>

        <div class="row">
            <div class="col-sm-12 titulo">
                <h4> Alta de Producto</h4>
            </div>
        </div>

        <div class="form2">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            <form novalidate='True' id="alta-form" name="alta-form" action="{% url 'appRP:alta_producto' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-row">

                    {% for field in alta_form %}
                    {% if field.name == 'formato' or field.name == 'precio' %}
    
                    <div class="form-group col-md-12">
                        {{ field.label_tag }}
                        {{ field }}                    
                    </div>
    
                    {% else %}    
                    <div class="form-group col-12">
                        {{ field.label_tag }}
                        {{ field }}                      
                    </div>            
                    {% endif %}
                    <div>{{field.errors}}</div>
                    {% endfor %}

                </div>
                <button class="btn btn-primary" type="submit">Enviar</button>
            </form>

        </div>

    </div>
</main>

{% endblock contenido %}

{% block javascript %}

{% endblock javascript %}

rpdesign/templates/appRP/publica/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    
    {% load static %}
    <link href="{% static 'css/styles.css' %}?v={% now 'U' %}" rel="stylesheet"> 
    <title>RP design {% block titulo %} {% endblock titulo %}</title>
</head>

<body>
    <div id="contenedor">
        <div class="container2">
            <header>
                <div class="svg2">
                    {% load static %}
                    <object type="image/svg+xml" src="{% static 'images/header2.svg' %}" class="svg-content">
                    </object>
                </div>
            </header>

            {% if barra == 'nav' %}

                {% include "./nav.html" %}
            
            {% else %}
            
                {% include "./nav2.html" %}
            
            {% endif %}
        </div>

        {% block contenido %}

        {% endblock contenido %}

        {% include "./footer.html" %}
        
        <script src="https://kit.fontawesome.com/7b27addec7.js" crossorigin="anonymous"></script>
        <script src="https://sdk.mercadopago.com/js/v2"></script>

        {% block javascript %}

        {% endblock javascript %}
    </div>
</body>
</html>

rpdesign/templates/appRP/publica/cancelado.html
{% extends './base.html' %}

{% block titulo %} - Cancelado {% endblock titulo %}

{% block contenido %}
<main>
    <div class="container3">
        <div class="separador"></div>
        <h1> "La compra ha sido cancelada" </h1>
        <div class="separador"></div>
        <p>El pago no fue realizado</p>
        <a class="contact" href="mailto:rpdesign@rpdesign.com.ar"> rpdesign@rpdesign.com.ar </a>
        <div class="separador"></div>
        <p class="main"></p>
    </div>
</main>
{% endblock contenido %}

rpdesign/templates/appRP/publica/carrito.html
{% extends './base.html' %}

{% block titulo %} - Carrito {% endblock titulo %}

{% block contenido %}

<main>
  <div class="container3">
    <div class="separador"></div>
    
    {% if user.is_authenticated %}
      <h1> "Bienvenido {{ user.first_name|lower }} a RP design" </h1>
    {% else %}
      <h1> "Bienvenido a RP design" </h1>
    {% endif %}

        <h1>Productos en el Carrito</h1>
          <table>
            <thead>
              <tr>
                  <th>Imagen</th>
                  <th>Producto</th>
                  <th>Cantidad</th>
                  <th>Remover</th>
                  <th>Precio Unitario</th>
                  <th>Importe</th>
              </tr>
            </thead>
            <tbody>
              {% for item in carrito %}
                {% with producto=item.producto %}
                <tr>
                  <td>
                    <a href="{{ producto.get_absolute_url }}">
                      <img src="{{producto.imagen.url}}" height="75px" alt="{{producto.name}}">
                    </a>
                  </td>
                  <td>{{ producto.nombre }}</td>
                  <td>
                    <form action="{% url "appRP:carrito_add" producto.id %}" method="post">
                      {{ item.actualizar_cantidad_form.cantidad }}
                      {{ item.actualizar_cantidad_form.anular }}
                      <input type="submit" value="Actualizar">
                      {% csrf_token %}
                    </form>
                  </td>
                  <td>
                    <form action="{% url "appRP:carrito_remove" producto.id %}" method="post">
                      <input type="submit" value="Remover">
                      {% csrf_token %}
                    </form>
                  </td>
                  <td class="num">${{ item.precio }}</td>
                  <td class="num">${{ item.precio_total }}</td>
                </tr>
                {% endwith %}
              {% endfor %}
                <tr class="total">
                  <td>Importe Total</td>
                  <td colspan="4"></td>
                  <td class="num">${{ carrito.get_precio_total }}</td>
                </tr>
            </tbody>
          </table>
          <div class="separador"></div>

        <p class="text-right">
        <a href="{% url "appRP:decoracion" %}" class="buttoncont">Continuar comprando</a>
        <a href="{% url "appRP:crear_orden" %}" class="buttonout"><i class="fa fa-check-circle"></i>Checkout</a>
        </p>
   
  </div>
</main>








{% endblock contenido %}

rpdesign/templates/appRP/publica/contact.html
{% extends './base.html' %}

{% block titulo %} - Contacto {% endblock titulo %}

{% block contenido %}
<main>
    <div class="container3">
        <div class="separador"></div>
        <h1> "Contactenos" </h1>
        {{ titulo|title }}
        <div class="separador"></div>
        <p>Escribanos a:</p>
        <a class="contact" href="mailto:rpdesign@rpdesign.com.ar"> rpdesign@rpdesign.com.ar </a>
        <div class="separador"></div>
        <p class="main">Personalmente en Villa del Parque</p>
        <a class="contact" href="https://goo.gl/maps/jz2rqpRmJ3fn2JmG6" target="_blank">Av. Francisco Beiró
            3200</a>
        <div class="separador"></div>
        <div class="maps">
            <iframe class="mapa_contacto"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4020.121119804454!2d-58.50063737072891!3d-34.59735791328391!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb6309768763f%3A0xa46660c736627764!2sAv.%20Francisco%20Beir%C3%B3%203200%2C%20C1419HYS%20CABA!5e0!3m2!1ses-419!2sar!4v1629481903526!5m2!1ses-419!2sar"
                width="23%" height="300" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>
</main>
{% endblock contenido %}

rpdesign/templates/appRP/publica/detalle.html
{% extends './base.html' %}

{% block titulo %} - Decoracion {% endblock titulo %}

{% block contenido %}

<main>
    <section>
        <div class="container3">
            <div class="separador"></div>
            {% if user.is_authenticated %}
              <h1> "Bienvenido {{ user.first_name|lower }} a RP design" </h1>
            {% else %}
              <h1> "Bienvenido a RP design" </h1>
            {% endif %}

              <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    {% load static %}
                    <img src={% get_media_prefix %}{{producto.imagen}} alt={{producto.nombre}} class="img-fluida rounded-start">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{producto.nombre}}</h5>
                      <p class="card-text">{{producto.descripcion}}</p>
                      <p class="card-text"><small class="text-muted">Formato disponible {{producto.formato}}</small></p>
                      <div class="card-text">
                        <p>$ {{producto.precio}}.-</p>
                      </div>
                      <form action="{% url "appRP:carrito_add" producto.id %}" method="post">
                        {{ carrito_producto_form }}
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                            <input type="submit" value="Agregar al Carrito" class="card-submit">
                        {% else %}
                            <input type="button" value="Agregar al Carrito" class="card-button">
                        {% endif %}
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              <div class="overlay" id="overlay">
                <div class="popup" id="popup">
                  <a href="#" id="btn-cerrar-popup" class="btn-cerrar-popup"><i class="bi bi-x-square-fill"></i> </a>
                  <div class="svgpop">
                      {% load static %}
                      <img src="{% static 'images/logo2.svg' %}" alt="RPdesign">
                    </div>
                  <h2>"para poder comprar debe iniciar sesión"</h2>
                </div>
              </div>

        </div>
    </section>
</main>


{% endblock contenido %}


{% block javascript %}
  {% load static %}
    <script src="{% static 'js/popup.js' %}"></script>
{% endblock javascript %}

rpdesign/templates/appRP/publica/edita_usuario.html
{% extends './base.html' %}

{% block titulo %} - Alta usuario {% endblock titulo %}

{% block contenido %}

<main>
  <div class="container3">
    <div class="separador"></div>

    {% if user.is_authenticated %}
      <h1> "Bienvenido {{ user.first_name|lower }} a RP design" </h1>
    {% else %}
      <h1> "Bienvenido a RP design" </h1>
    {% endif %}

    
    <div>
      <h4> Edición de usuario </h4>
    </div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
    {{ message }}
    </div>
    {% endfor %}

    <div class="form2">
      <form novalidate='True' id="altau-form" name="altau-form" action="{% url 'appRP:editar_usuario' user.id %}"  method="POST" onsubmit="return validarForm()" >
        {% csrf_token %}

        <div class="form-row">

          {% for field in modu_form %}

            {{ field.label_tag }}
            {{ field }}
            
          {% endfor %}

        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
    </div>
  </div>
</main>

{% endblock contenido %}

{% block javascript %}
  {% load static %}
    <script src="{% static 'js/validar.js' %}"></script>
{% endblock javascript %}

rpdesign/templates/appRP/publica/lista_productos.html
{% extends './base.html' %}

{% block titulo %} - Alta productos {% endblock titulo %}

{% block contenido %}
<main>
    <div class="container3">
        <div class="separador"></div>
        <h1> "Listado de productos" </h1>

            <div>
                <table class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Producto</th>
                            <th>Descripción</th>
                            <th>Formato</th>
                            <th>Precio</th>
                            <th>Foto</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                            <th>Disponible</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                        <tr>
                            <td>{{producto.id}}</td>
                            <td>{{producto.nombre}}</td>
                            <td>{{producto.descripcion}}</td>
                            <td>{{producto.formato}}</td>
                            <td>{{producto.precio}}</td>
                            <td><img src="{{producto.imagen.url}}" height="75px" alt="{{producto.name}}"></td>

                            <td><a href="{% url "appRP:edita_producto" producto.id %}"><i
                                        class="bi bi-pencil" style="font-size: 1.5rem; color: #009599;"></i></a>
                            </td>
                            <td><a onclick="return confirm('¿Realmente desea eliminar este producto?')" 
                                    href="{% url "appRP:elimina_producto" producto.id %}"><i
                                        class="bi bi-trash" style="font-size: 1.5rem; color: #009599;"></i></a>
                            </td>
                            <td>{% if producto.disponible %} Si {% else %} No {% endif %}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
</main>


{% endblock contenido %}

rpdesign/templates/appRP/publica/login.html
{% extends './base.html' %}

{% block titulo %} - Login {% endblock titulo %}

{% block contenido %}
<main>
    <div class="container3">
        <div class="separador"></div>
        <h1> "Bienvenido a RP design" </h1>
        <div class="separador"></div>
            {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
            </div>
            {% endfor %}
        <form id="login" name="login" action="{% url 'appRP:login' %}" method="POST">
            <div class="form">{% csrf_token %}
                {% for field in form %}

                {{ field.label_tag }}
                {{ field }}
                
                {% endfor %}
                <button class="btn btn-primary" type="submit">Iniciar sesión</button>
                <p class="message">No esta registrado? <a href="{% url 'appRP:alta_usuario' %}">Crea una cuenta</a></p>
            </div>
        </form>
        <div class="separador"></div>
    </div>
</main>
{% endblock contenido %}

rpdesign/templates/appRP/publica/nav.html
            <nav>
                <div class="barra">
                </div>
            </nav>